use_frameworks!

target 'StompClientLib_Example' do
  pod 'StompClientLib', :path => '../'

  target 'StompClientLib_Tests' do
    inherit! :search_paths

    pod 'SocketRocket'
    
  end
end
target 'StompClientLib_Example_tvOS' do
  pod 'StompClientLib', :path => '../'

end
